ClubActiveCenter/ClubActiveCenter

back/index.js
La funcion de sumar ya esta terminada
=> Funcion terminada

back/active-center/.env.example, back/active-center/package-lock.json, back/active-center/package.json, back/active-center/src/app.module.ts, back/active-center/src/config/cloudinary.ts, back/active-center/src/config/config.module.ts, back/active-center/src/config/typeorm.ts, back/active-center/src/main.ts
Agregue la configuración de .env , la conexión de la DB y Cloudinary
=> Config TypeOrm , Cloudinary and env.example

back/active-center/package-lock.json, back/active-center/src/config/swagger.config.ts, back/active-center/src/main.ts
=> added swagger

front/club-deportivo/src/app/home/page.tsx, front/club-deportivo/src/components/InfoHome.tsx
=> se inicio el Home parte-1

back/active-center/src/Auth/auth.service.ts, back/active-center/src/Auth/roles.enun.ts, back/active-center/src/decorators/roles.decorator.ts, back/active-center/src/guards/roles.guard.ts
se creo el decorador para aplicar roles. se agrego los roles en la firma del token.
=> rolesUsuario

front/club-deportivo/src/app/instalaciones/[slug]/page.tsx
corregi el error de promesa en el slug
=> se corrigio el error de slug

front/club-deportivo/src/app/actividades/[slug]/page.tsx, front/club-deportivo/src/app/instalaciones/[slug]/page.tsx, front/club-deportivo/src/components/Footer.tsx, front/club-deportivo/src/components/HomeInfo/ActivitiesSection.tsx, front/club-deportivo/src/components/HomeInfo/BeneficiosInfo.tsx, front/club-deportivo/src/components/HomeInfo/InfoHome.tsx, front/club-deportivo/src/components/Nav.tsx
cambie las imagenes por las de cloudinary
=> Cambio imagenes

front/club-deportivo/src/app/actividades/[slug]/page.tsx, front/club-deportivo/src/app/actividades/page.tsx, front/club-deportivo/src/config/navConfig.ts, front/club-deportivo/src/context/activityContext.tsx, front/club-deportivo/src/interface/IActivity.ts
Cree la pagina de actividades, creare proximamente el dashbord de admin.
=> Pagina actividades

front/club-deportivo/package-lock.json, front/club-deportivo/package.json, front/club-deportivo/src/app/adminDashboard/page.tsx, front/club-deportivo/src/components/AddActivityModal.tsx, front/club-deportivo/src/components/StatCard.tsx
Hice la parte 1 del dashboard de administrador.
=> Admin dashboard

front/club-deportivo/next.config.ts, front/club-deportivo/package-lock.json, front/club-deportivo/package.json, front/club-deportivo/src/app/api/auth/[...auth0].ts, front/club-deportivo/src/app/api/auth/[...auth0]/route.ts, front/club-deportivo/src/components/Login/Login.tsx
=> se completo auth0

front/club-deportivo/src/app/cart/page.tsx, front/club-deportivo/src/components/IconosMenu/CartButton.tsx, front/club-deportivo/src/components/Nav.tsx, front/club-deportivo/src/context/CartContext.tsx
carrito parte 1 hecha, mas el contexto.
=> carrito parte 1

back/active-center/package-lock.json, back/active-center/package.json, back/active-center/src/Entities/Order.entity.ts, back/active-center/src/Entities/Payment.entity.ts, back/active-center/src/Entities/Product.entity.ts, back/active-center/src/Entities/User.entity.ts, back/active-center/src/Payment/PaymentDTO/payment.dto.ts, back/active-center/src/Payment/payment.controller.ts, back/active-center/src/Payment/payment.module.ts, back/active-center/src/Payment/payment.service.ts, back/active-center/src/Product/product.controller.ts, back/active-center/src/Product/product.module.ts, back/active-center/src/Product/product.service.ts, back/active-center/src/Product/productDTO/product.dto.ts, back/active-center/src/app.module.ts, back/active-center/src/config/typeorm.ts, back/active-center/src/main.ts
Descripción:
Este PR implementa un sistema de pagos utilizando Stripe Checkout y la creación de productos con control de estado basado en el stock. El flujo de pago es el siguiente:
Flujo de pago con Stripe Checkout:
Crear sesión de pago (createCheckoutSession):
Se recibe el orderId y userId.
Se obtiene la orden desde la base de datos.
Se genera una sesión de pago de Stripe con los productos de la orden.
Se devuelve la URL de pago para redirigir al usuario.
Webhook de Stripe (handleWebhook):
Stripe envía un evento cuando se completa un pago.
Se valida el evento con la firma de seguridad utilizando la clave STRIPE_WEBHOOK_SECRET.
Se obtiene la orden y el usuario desde la base de datos.
Se crea un registro de pago en la base de datos.
Se cambia el estado de la orden a complete.
Flujo de …
=> Payment/Products Primera parte 

front/club-deportivo/src/app/layout.tsx, front/club-deportivo/src/components/IconosMenu/UserMenu.tsx, front/club-deportivo/src/components/Nav.tsx, front/club-deportivo/src/lib/auth0-config.ts
Se casi termino el login con auth0
=> Cambios Login auth0

front/club-deportivo/src/app/product/[slug]/page.tsx, front/club-deportivo/src/components/Botones/AddProduct.tsx, front/club-deportivo/src/components/Card/Card.tsx, front/club-deportivo/src/components/Productos/productContainer.tsx, front/club-deportivo/src/helpers/getProduct.ts, front/club-deportivo/src/helpers/getProducts.ts
se hizo el slug de productos y el container.
=> slug de productos y otros cambios

front/club-deportivo/src/app/product/[slug]/page.tsx, front/club-deportivo/src/components/Card/Card.tsx, front/club-deportivo/src/components/Productos/productContainer.tsx, front/club-deportivo/src/helpers/getProduct.ts, front/club-deportivo/src/helpers/getProducts.ts
Se visualizaron los productos en la tienda, proximamente se intentara que se vea la especificacion.
=> Pruebas productos

front/club-deportivo/package-lock.json, front/club-deportivo/package.json, front/club-deportivo/src/app/instalaciones-2/page.tsx, front/club-deportivo/src/app/product/[slug]/page.tsx, front/club-deportivo/src/components/Botones/AddProduct.tsx, front/club-deportivo/src/components/Carousel/InstalacionesSlider.tsx, front/club-deportivo/src/components/IconosMenu/CartButton.tsx, front/club-deportivo/src/helpers/getInstalacion.ts, front/club-deportivo/src/helpers/getProduct.ts, front/club-deportivo/src/helpers/getProducts.ts, front/club-deportivo/src/interface/IIntalacion.ts
=> correccion de errores ignacia

front/club-deportivo/src/app/cart/page.tsx, front/club-deportivo/src/app/layout.tsx, front/club-deportivo/src/components/Botones/AddProduct.tsx, front/club-deportivo/src/components/IconosMenu/CartButton.tsx, front/club-deportivo/src/components/IconosMenu/UserMenu.tsx, front/club-deportivo/src/context/CartContext.tsx, front/club-deportivo/src/helpers/getProduct.ts, front/club-deportivo/src/interface/IIntalacion.ts
Se creo el carrito de compras.
=> se realizo el carrito de compras

back/active-center/src/Reservation/ReservationDTO/reservations.dto.ts, back/active-center/src/Reservation/ReservationDTO/update-reservation.dto.ts, back/active-center/src/Reservation/reservation.controller.ts, back/active-center/src/Reservation/reservation.service.ts, back/active-center/src/Reservation/validator.ts
se creo endpoint para actualizar reserva , se retiro el price del dto ya q no se pasa se busca de la base de datos.
se arreglo validacion de hora , no andaba.
se agrego endpoint para cancelar reserva.
se documentaron las rutas.
=> faltanteReservas

front/club-deportivo/src/components/Botones/BotonReserva.tsx, front/club-deportivo/src/components/IconosMenu/UserMenu.tsx, front/club-deportivo/src/components/RutasMenu/AdminRoute.tsx, front/club-deportivo/src/context/AuthContext.tsx, front/club-deportivo/src/context/CartContext.tsx
Hice cambios en el authContext.
=> cambios en el authContext

front/club-deportivo/next.config.ts, front/club-deportivo/src/app/adminDashboard/page.tsx, front/club-deportivo/src/components/IconosMenu/UserMenu.tsx, front/club-deportivo/src/components/RutasMenu/AdminRoute.tsx, front/club-deportivo/src/context/AuthContext.tsx
hice cambios al authContext parte 2
=> cambios authContext 2

back/active-center/src/Cart/cart.service.ts, back/active-center/src/Order/order.service.ts, back/active-center/src/Payment/payment.service.ts, back/active-center/src/Reservation/reservation.controller.ts, back/active-center/src/Reservation/reservation.module.ts, back/active-center/src/Reservation/reservation.service.ts, back/active-center/src/Space/space.controller.ts, back/active-center/src/Space/space.module.ts, back/active-center/src/Space/space.service.ts
Implementación de búsqueda de reservas por ID de usuario, creación de espacios con imagen y manejo de excepciones
- Añadida ruta para buscar reservas por ID de usuario en el servicio de reservas.
- Implementado servicio para crear espacios con imagen, utilizando Cloudinary para el almacenamiento de imágenes.
- Se han agregado excepciones para manejo de errores en procesos de orden, pago y carrito.
=> Búsqueda de reservas, creación de espacios con imagen y manejo de excepciones

back/active-center/src/Cart/cart.controller.ts, back/active-center/src/Cart/cartDTO/cart.dto.ts, back/active-center/src/Order/OrderDTO/orders.dto.ts, back/active-center/src/Order/order.controller.ts, back/active-center/src/Order/order.service.ts, back/active-center/src/Payment/payment.controller.ts, back/active-center/src/Payment/payment.service.ts, back/active-center/src/Reservation/ReservationDTO/reservations.dto.ts, back/active-center/src/config/typeorm.ts
Documentación de las API: Se agregaron las decoraciones @ApiOperation en las rutas de orders, cart y payment para proporcionar un resumen y descripción claros de lo que hace cada endpoint. Esto facilita las pruebas y mejora la comprensión de los servicios.
Ajustes en el webhook: Se realizó un pequeño ajuste en la ruta del webhook para manejar correctamente la verificación de la firma de Stripe y responder adecuadamente según el estado del proceso.
Mejora en los GET de órdenes: Se mejoró el manejo de la respuesta en las rutas de obtención de órdenes, ahora se incluyen las órdenes filtradas por usuario, lo que facilita la consulta y evita la confusión al recibir los datos.
=> "Documentación de APIs y mejoras en manejo de órdenes y webhook"

front/club-deportivo/src/app/actividades/page.tsx, front/club-deportivo/src/app/admin/actividades/page.tsx, front/club-deportivo/src/components/admin/ActivitiesTable.tsx, front/club-deportivo/src/context/AdminContext.tsx, front/club-deportivo/src/interface/IActivity.ts
se realizaron funcionalidades a las actividades en el admin.
=> funcionalidades admin

front/club-deportivo/src/service/AuthServiceRegistro.ts.ts, front/club-deportivo/src/service/authservices.ts, front/club-deportivo/src/service/createReservasService.ts, front/club-deportivo/src/service/reservasServices.ts, front/club-deportivo/src/service/user.ts
se hacen las conexiones al deploy , no se protengen las rutas porque el login me pide que sea a /api y los demas no , despues protejo las variables de mis codigos
=> Agusparadeploy

back/active-center/src/webSockets/websocket.gateway.ts
=> cambios chat

back/active-center/src/Entities/Space.entity.ts, back/active-center/src/Entities/SubscriptionDetails.entity.ts, back/active-center/src/Payment/payment.controller.ts, back/active-center/src/Payment/payment.module.ts, back/active-center/src/Payment/payment.service.ts, back/active-center/src/Space/space.service.ts, back/active-center/src/Subscription/subscription.controller.ts, back/active-center/src/Subscription/subscription.module.ts, back/active-center/src/Subscription/subscriptions.service.ts
arregle la carga de imágenes de espacios
implemente funcionalidad de pago a la suscripción al suscribirse genera link de pago , y al completar el pago si fue confirmado se suscribe si no no se suscribe al plan.
=> se arreglo la carga de iamgenes del seeder space, paso Subs

front/club-deportivo/src/app/actividades/page.tsx, front/club-deportivo/src/app/admin/productos/page.tsx, front/club-deportivo/src/app/cart/page.tsx, front/club-deportivo/src/app/tienda/page.tsx, front/club-deportivo/src/components/IconosMenu/CartButton.tsx, front/club-deportivo/src/components/admin/CreateProductModal.tsx, front/club-deportivo/src/components/admin/ProductsTable.tsx, front/club-deportivo/src/context/AdminContext.tsx, front/club-deportivo/src/context/CartContext.tsx, front/club-deportivo/src/helpers/getProduct.ts, front/club-deportivo/src/helpers/getProducts.ts, front/club-deportivo/src/interface/IProducts.ts, front/club-deportivo/src/utils/mapProductData.ts
cambios de productos, se implemento el agregar productos parte 1.
=> Cambios productos

back/active-center/src/Entities/Activity.entity.ts, back/active-center/src/Subscription/subscriptions.service.ts, front/club-deportivo/src/app/home/page.tsx, front/club-deportivo/src/components/SendUserData.tsx, front/club-deportivo/src/context/AuthContext.tsx
=> Cambios ale

back/active-center/src/webSockets/websocket.gateway.ts
se instalo sockjs para q la comunicacion siga funcionando en render
=> implementacion de sockjs
